const products = [
    {
      id: 1,
      name: 'Телефон Sony',
      category: 'electronics',
      price: 15000,
      brand: 'sony',
    },
    {
      id: 2,
      name: 'Наушники Samsung',
      category: 'electronics',
      price: 3000,
      brand: 'samsung',
    },
    {
      id: 3,
      name: 'Футболка Nike',
      category: 'clothes',
      price: 1500,
      brand: 'nike',
    },
    {
      id: 4,
      name: 'Кроссовки Adidas',
      category: 'clothes',
      price: 5000,
      brand: 'adidas',
    },
    {
      id: 5,
      name: "Книга 'JavaScript'",
      category: 'books',
      price: 800,
      brand: 'all',
    },
    {
      id: 6,
      name: 'Телевизор Samsung',
      category: 'electronics',
      price: 25000,
      brand: 'samsung',
    },
    {
      id: 7,
      name: 'Шорты Nike',
      category: 'clothes',
      price: 1200,
      brand: 'nike',
    },
    {
        id: 8,
        name: 'Планшет Sony',
        category: 'electronics',
        price: 18000,
        brand: 'sony',
      },
    ]